# Site settings
title: "Online Resume"
description: "An online resume template with the help of Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Amit R. Shah"
resume_title:                   "CTO at Infopercept Consulting"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "amit.r.shah.2005@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "9408820985"
resume_contact_address:         "Ahmedabad, Gujarat, India"

resume_header_contact_info:     "Ahmedabad, Gujarat, India • 9408820985 • amit.r.shah.2005@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>A goal oriented person, who wants to complete his goal anyhow by providing quality work on time. Want to stand by as an individual in the industry which i am working in.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/shahamitr/resume-template"
  resume_twitter_url:           "https://twitter.com/amitshah001"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/amit-shah-132b3010/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
